name: tessellationapp
version: 2.0.0
description: Tessellation
authors:
  - David Rasch <david@cloudscripting.nl>
homepage: https://www.cloudscripting.nl/tessellations/

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
