name: tessellationapp
version: 2.0.0
description: Tessellation
authors:
  - David Rasch <david@cloudscripting.nl>
homepage: https://www.cloudscripting.nl/tessellations/

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  path_provider:
  flutter_colorpicker:
  share:
    path: plugins/share

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
    - lib/square90.json
    - lib/brick.json
    - lib/diamond.json
    - lib/hexagon.json
