name: tessellation
version: 2.1.5+11
description: Tessellation
homepage: https://www.cloudscripting.nl/tessellations/

environment:                                                            
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  vector_math: ^2.1.0
  path_provider: ^2.0.1
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.0.1
  undo: ^1.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
    - lib/square90.json
    - lib/brick.json
    - lib/diamond.json
    - lib/hexagon.json
