name: tessellation
version: 2.1.5+11
description: Tessellation
homepage: https://www.cloudscripting.nl/tessellations/

environment:                                                            
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  vector_math: ^2.1.0
  path_provider: ^2.0.1
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^1.2.0
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
    - lib/square90.json
    - lib/brick.json
    - lib/diamond.json
    - lib/hexagon.json
