name: tessellationapp
version: 2.1.4+10
description: Tessellation
authors:
  - David Rasch <david@cloudscripting.nl>
homepage: https://www.cloudscripting.nl/tessellations/

environment:                                                            
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  vector_math: ^2.1.0
  path_provider: ^2.0.1
  flutter_colorpicker: ^0.4.0-nullsafety.0 
  flutter_slidable: ^0.6.0-nullsafety.0
  share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
    - lib/square90.json
    - lib/brick.json
    - lib/diamond.json
    - lib/hexagon.json
