name: tessellationapp
version: 2.0.0
description: Tessellation
authors:
  - David Rasch <david@cloudscripting.nl>
homepage: https://www.cloudscripting.nl/tessellations/

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  barback:
  path:
  flutter_color_picker: {path: flutter_color_picker-0.0.1}

dependency_overrides:
  sky_engine:
    path: /Users/david/src/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_engine
  sky_services:
    path: /Users/david/src/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_services

flutter:
  uses-material-design: true
  assets:
    - lib/square.json
    - lib/triangle.json
    - lib/square90.json
    - lib/brick.json
    - lib/diamond.json
    - lib/hexagon.json

#transformers:
#  - tessellationapp/icon_resizer:
#      $include: "lib/icon.svg"
