name: Android APK Build 
# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main
jobs:
  build-android:
    # Define the job to run on the latest Ubuntu environment
    runs-on: ubuntu-latest
    steps:
        # Checkout the repository to get access to the code
      - name: Checkout repository
        uses: actions/checkout@v3        
      
        # Set up Flutter environment using the stable channel
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 
          architecture: x64 
          
        # Install Flutter dependencies from pubspec.yaml
      - name: Install dependencies
        run: flutter pub get
        
        # Set up JDK 17 required for building Android applications
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Use Zulu distribution of Java
          java-version: '17'     # Specify Java version 17
        
        # Create relevant secret files for the Android build
      - name: Create relevant secret files
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
          EOF        
        
        # Decode the Base64 encoded keystore & save it as a .jks file
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt             
          base64 -d keystore-b64.txt > android/app/keystore.jks
          
        # Build the Android APK as an App Bundle (AAB) for release
      - name: Build Android APK
        run: flutter build appbundle --release      

        # Upload the artifact
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: android-AAB
          path: build/app/outputs/bundle/release/*.aab
